import os
import json
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import shap
from flaml import AutoML
from sklearn.model_selection import train_test_split

# Ensure the outputs directory exists
os.makedirs("outputs", exist_ok=True)

def execute_cleaning_code(df, code_string):
    """
    Safely executes the Python code generated by Gemini to clean the dataframe.
    Expects the code_string to define a function named 'clean_data(df)'.
    """
    try:
        # Create a dictionary to act as the local namespace for the exec() function
        local_namespace = {}
        
        # Execute the string as Python code. This loads the 'clean_data' function into memory.
        exec(code_string, globals(), local_namespace)
        
        # Check if Gemini actually named the function 'clean_data' as instructed
        if 'clean_data' in local_namespace:
            clean_data_func = local_namespace['clean_data']
            # Run the function on our dataframe
            cleaned_df = clean_data_func(df.copy())
            return cleaned_df, "Success"
        else:
            return df, "Error: The AI did not generate a function named 'clean_data'."
            
    except Exception as e:
        return df, f"Error executing cleaning code: {str(e)}"

def train_flaml_model(df, target_column, task_type, time_budget=60):
    """
    Trains an AutoML model using FLAML and saves the best model and metadata.
    """
    if target_column not in df.columns:
        raise ValueError(f"Target column '{target_column}' not found in the dataset.")

    # Separate features (X) and target (y)
    X = df.drop(columns=[target_column])
    y = df[target_column]
    
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Initialize FLAML AutoML
    automl = AutoML()
    
    # Configure settings based on what Gemini detected (Classification or Regression)
    # We convert Gemini's output to lowercase to match FLAML's expected input
    automl_settings = {
        "time_budget": time_budget,  # How many seconds to search for the best model
        "metric": 'accuracy' if task_type.lower() == 'classification' else 'r2',
        "task": task_type.lower(),
        "log_file_name": "outputs/flaml.log",
        "seed": 42
    }
    
    # Run the training process
    automl.fit(X_train=X_train, y_train=y_train, **automl_settings)
    
    # Save the best model as a .pkl file
    model_path = "outputs/best_model.pkl"
    joblib.dump(automl, model_path)
    
    # Save metadata so our Predictor UI knows exactly what inputs to ask the user for later
    metadata = {
        "target_column": target_column,
        "task_type": task_type,
        "features": list(X.columns),
        "best_estimator": automl.best_estimator,
        "best_config": automl.best_config
    }
    
    with open("outputs/model_meta.json", "w") as f:
        json.dump(metadata, f, indent=4)
        
    return automl, X_test, metadata

def generate_shap_plot(model, X_test):
    """
    Generates a SHAP feature importance plot for explainability.
    """
    try:
        # We need the actual underlying estimator (like XGBoost or LightGBM) from FLAML
        estimator = model.model.estimator
        
        # Create a SHAP explainer
        explainer = shap.Explainer(estimator, X_test)
        shap_values = explainer(X_test)
        
        # Create the plot using Matplotlib
        plt.figure(figsize=(10, 6))
        
        # Depending on the model type, SHAP values can be a list or a single array
        if isinstance(shap_values.values, list):
             shap.summary_plot(shap_values.values[1], X_test, show=False)
        else:
             shap.summary_plot(shap_values, X_test, show=False)
             
        # Grab the current figure so Streamlit can render it
        fig = plt.gcf()
        return fig
        
    except Exception as e:
        print(f"SHAP generation failed: {str(e)}")
        return None
